name: Sync with Upstream (Mirror)

on:
  schedule:
    - cron: "0 6 * * *"   # täglich um 06:00 UTC
  workflow_dispatch:       # manuelles Auslösen möglich

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout fork
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add upstream remote
        run: |
          git remote remove upstream || true
          git remote add upstream https://github.com/MilosKozak/AndroidAPS.git

      - name: Fetch upstream (branches + tags)
        run: git fetch upstream --prune --tags

      - name: Hard reset fork branch to upstream
        run: |
          git checkout master   # falls dein Default-Branch "main" ist, hier anpassen
          git reset --hard upstream/master

      - name: Push branch + tags back to fork
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Remote origin neu setzen mit Token-Auth
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git
          
          git push origin master --force
          git push origin --tags --force
